backend:
  name: git-gateway
  branch: master

media_folder: "static/images/uploads"
public_folder: "/images/uploads"
collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "assets/content/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    format: 'json'
    sort: "date:desc" # Default is title:asc
    fields: # The fields for each document, usually in front matter
      - {label: "Featured image", name: "featured-image", widget: "image", required: true}
      - {label: "Product title", name: "title", widget: "string", required: true}
      - {label: "Brand", name: "brand", widget: "string", required: true}}
      - {label: "Publish Date", name: "date", widget: "date", format: "Do MMM YYYY"}
      - {label: "Body", name: "body", widget: "markdown"}
